### PR TITLE
PCH Related Posts: Fix hang under edge cases

### PR DESCRIPTION
**Pull request by vaurdan**
## Description

Backport of #2432 for 3.14.4 release

### CODE REVIEW

**Comment by acicovic** [comment]
Is this different from https://github.com/Parsely/wp-parsely/pull/2432 in any way?

**Comment by vaurdan** [comment]
@acicovic not really, this one is the same but with the [prepare/3.14.4-release](https://github.com/Parsely/wp-parsely/tree/prepare/3.14.4-release) base branch. But now I noticed that #2432 is also tracking that branch, so maybe this one is unnecessary?

**Comment by acicovic** [comment]
Yes, I think this PR is a duplicate. I just wanted to make sure that you haven't done anything special here.

**Comment by acicovic** [comment]
The original PR was against 3.14.3 from its creation. There was never a 3.15 version of it.

**Comment by vaurdan** [comment]
Let's close it, then!

Duplicate of #2432

**Pull request closed without merging**
