### PR TITLE
Improve plugin page on wordpress.org 

### LINKED ISSUE #609: Improve plugin page on wordpress.org
## Is your feature request related to a problem?
Our [wordpress.org plugin page](https://wordpress.org/plugins/wp-parsely/) could use some love. For example, as a beginning we could add more tags and fix the page's current display problems. Also, it seems that the plugin page doesn't completely obey to our README.md (for example, we do have extra tags in our README.md). Our plugin page is our interface with the world, so we should be able to manipulate it as best as possible.

## Describe the solution you'd like
Create a readme.txt file to be able to control the plugin's page contents. My understanding is that this will also allow us to have a different readme for the plugin's page and another one for this repository (which is be default the README.md).

Related material:
- [readme.txt documentation](https://developer.wordpress.org/plugins/wordpress-org/how-your-readme-txt-works/).
- The [readme.txt from Yoast](https://github.com/Yoast/wordpress-seo/blob/trunk/readme.txt) can be used as a reference as it contains everything (screenshots, FAQs, code blocks) and I think it powers everything in [their plugin page](https://wordpress.org/plugins/wordpress-seo/).

### PR DESCRIPTION
**Pull request by acicovic**
## Description
This PR solves some of the issues in our [plugin page](https://wordpress.org/plugins/wp-parsely/) that are described [here](https://github.com/Parsely/wp-parsely/issues/609#issuecomment-1019801977).

## Motivation and Context
Fixes #609

## How Has This Been Tested?
Making changes and previewing them.

### CODE REVIEW

**Comment by GaryJones** [comment]
The same Basic Settings are now shown three times in the first three updated screenshots - this seems excessive and doesn't help to focus on how this plugin can help the user.

I wouldn't bother highlighting the presence of Help or Screen Options - they are nice-to-have features, but they don't need to be the focus of screenshots.

**Comment by acicovic** [comment]
> The same Basic Settings are now shown three times in the first three updated screenshots - this seems excessive and doesn't help to focus on how this plugin can help the user.
> 
> I wouldn't bother highlighting the presence of Help or Screen Options - they are nice-to-have features, but they don't need to be the focus of screenshots.

Fair enough. What would you suggest?

**Comment by GaryJones** [comment]
What was wrong with [fresh] screenshots of the existing sections?

**Comment by acicovic** [comment]
So far we had a separate screenshot for each section (I guess not to have really long screenshots). This is not representative of how the plugin looks now, though whether this is a problem or not is personal opinion. I could go that route again (screenshot for every section) or just post a single screenshot with everything enabled in the options page (but this would be long).

**Comment by GaryJones** [comment]
> screenshot for every section

This looked fine and made most sense to me.

**Review by pauarge — DISMISSED** [review]
🚢 🚢 🚢

**Comment by acicovic** [comment]
I'm working on updating the second screenshot to include the new tracking table UI element.

**Comment by acicovic** [comment]
I think we should be good to go now.

**Review by GaryJones — APPROVED** [review]
✅

**Pull request merged**
