### PR TITLE
README.md: Update "Tested up to" to 6.1.1

### PR DESCRIPTION
**Pull request by acicovic**
## Description
This PR updates the "Tested up to" field of `README.md` to `6.1.1`.

## Motivation and Context
Keep our `README.md` updated with the latest information.

## How Has This Been Tested?
No code changes.

### CODE REVIEW

**Review by GaryJones — CHANGES_REQUESTED** [review]
> **Tested up to** – The version of WordPress that the plugin has been tested against. This field ignores minor versions, as plugins shouldn’t break with a minor update. This means a plugin only need to define the major version it is tested against and the WordPress.org plugin directory will automatically add the minor version.
-- https://developer.wordpress.org/plugins/wordpress-org/how-your-readme-txt-works/

**Comment by acicovic** [comment]
Nice find, I was totally unaware of that. So far we've been doing this manually.

**Comment by acicovic** [comment]
@GaryJones, have you seen this working in practice?

**Comment by GaryJones** [comment]
@acicovic If you look at the [readme for 3.5.2 in SVN](https://plugins.trac.wordpress.org/browser/wp-parsely/tags/3.5.2/README.md), you'll see it says tested up to `6.0.2`, but when you look at the sidebar of https://wordpress.org/plugins/wp-parsely/ then it shows `6.0.3`.

i.e. the readme only needed to say `6.0`, and it doesn't need PRs to bump the final extra digit.

**Comment by acicovic** [comment]
Closing in favor of #1197.

**Pull request closed without merging**
