### PR TITLE
Add a WINDOWS.md file for Windows developers

### PR DESCRIPTION
**Pull request by acicovic**
## Description
This PR introduces a WINDOWS.md file containing some troubleshooting/setup instructions for developers who work on Windows, so they can set up a fully working development environment. It also puts a couple of links in CONTRIBUTING.md towards WINDOWS.md in the related sections.

Thanks to @jblz for helping in finding the solution to the composer issue.

## Motivation and Context
Although we don't support Windows development officially, possible contributors might be working on Windows. Unfortunately, certain things don't seem to be working as expected out of the box in Windows, and this could be a deterrent factor to developers trying to contribute. This PR provides some help regarding that and is also a note to ourselves should we ever need to develop on Windows.

## How Has This Been Tested?
1. The problems described have been experienced on a Windows 10 installation.
2. After researching and doing trial and error operations, working solutions have been found.
3. The above working solutions were documented.

### CODE REVIEW

**Review by GaryJones — APPROVED** [review]
✅

**Review by pauarge — APPROVED** [review]
Great work!

This is out of the scope of this PR and I'm happy to merge, but I wonder if we should create in the future a `docs` folder where we hold documents like this one.

**Comment by acicovic** [comment]
> This is out of the scope of this PR and I'm happy to merge, but I wonder if we should create in the future a `docs` folder where we hold documents like this one.

I wondered about the same thing. We should probably see if anything would need to stay out of that directory (for example README.md).

**Comment by pauarge** [comment]
> I wondered about the same thing. We should probably see if anything would need to stay out of that directory (for example README.md).

Let's create an issue for it to keep track of the problem, but happy to merge this PR.

**Comment by acicovic** [comment]
> Let's create an issue for it to keep track of the problem, but happy to merge this PR.

Tracked in #621.

**Pull request merged**
