### PR TITLE
Widget: Hide the recommendation widget until the element is populated

### PR DESCRIPTION
**Pull request by jblz**
On my test site, I noticed that the Recommendations widget still shows even though no results are present to fill it.  The `getJSON` call (predictably) fails as this site is not registered in the system resulting in an empty div with my configured Title:

Screen Shot 2021-04-06 at 4 45 28 PM

This change defaults the widget's outermost div to `display: none;` and removes the pertinent class once the script has populated the div with content.

I'm sure this is an edge case that most customers will never hit, but, in the event of a failed API call, it'd probably be better to not show an empty widget.

### CODE REVIEW

**Review by GaryJones — DISMISSED** [review]
As per #156, I think we can do an even better approach, which is to show nothing on the front-end (like, no output at all), if the API details aren't populated in the options, and also change the widget form to a simple "Please head to the settings page and enter your API credentials"-type of message; that way, there's no expectation that the widget should be working but nothing appearing on the front-end.

I'm not keen on approach that visually hides the div with extra CSS (on every page that needs it) just for this edge case; I'd rather have less code sent to the browser to render when it's never going to work, not more.

Edit: Just realised that this was for a failed API call, not a lack of API credentials. Need to re-think my above response for this context.

**Review by GaryJones — COMMENTED** [review]
I've rescinded my previous Request Changes review, as I now understand better what the goal of this PR is. `#156` is a different issue.

Some thoughts:

 - the added class is `wpparsely_hidden`, but all of the other classes in the CSS file start with `parsely-recommended-widget` - so consider `.parsely-recommended-widget-hidden {...}` or something like `.parsely-recommended-widget.is-hidden {...}` (a la [SMACSS](http://smacss.com/book/type-state), and then remove `is-hidden`) to keep more of a consistency.
 - If the JSON arrival and rendering takes a second or so, would this "hide and then show" affect the layout shift? Next month Google makes CLS and other [Core Web Vitals](https://web.dev/vitals/) a ranking factor. Maybe it doesn't make a difference, unless with the new behaviour the whole container is hidden that was previously retaining space to avoid such a dramatic shift.

**Comment by jblz** [comment]
> If the JSON arrival and rendering takes a second or so, would this "hide and then show" affect the layout shift? Next month Google makes CLS and other Core Web Vitals a ranking factor. Maybe it doesn't make a difference, unless with the new behaviour the whole container is hidden that was previously retaining space to avoid such a dramatic shift.

This is a good point...

Perhaps we should have some fallback items that fill this space that we enable users to override or something.

> As per #156, I think we can do an even better approach, which is to show nothing on the front-end

Yeah, I definitely think we can do better than this during the effort to re-conceptualize the widget.  I mostly just noticed and wanted to make sure the issue was captured somewhere and I'd already spent the 5 minutes to figure out what was going on so flushed to a PR.

Let's go ahead and leave this on hold for now pending the other work, I think.

**Comment by pauarge** [comment]
I've migrated @jblz's changes to the new project structure (without jQuery and in a separate JS file).

**Review by pauarge — APPROVED** [review]

**Review by GaryJones — APPROVED** [review]

**Pull request merged**
