### PR TITLE
Update wordpress.org screenshots for settings page

### LINKED ISSUE #553: Update screenshot for settings page
3.1.0 of the plugin organised the settings page into new sections.
#552 fixed some strings on the settings page.

We should update `.wordpress-org/screenshot-1.png` to show the new settings page look (but hack locally to show the version as `3.1.0` first!).

### PR DESCRIPTION
**Pull request by acicovic**
## Description
This PR adds new settings page screenshots so they can be uploaded to the [plugin's page](https://wordpress.org/plugins/wp-parsely/) on wordpress.org.

## Motivation and Context

- As described in #553, the settings page has received some overhaul and the screenshot on the [plugin's page ](https://wordpress.org/plugins/wp-parsely/) doesn't reflect those changes. This PR fixes that.
- Fixes #553.

## Screenshots

image

image

image

### CODE REVIEW

**Review by GaryJones — CHANGES_REQUESTED** [review]
The README (https://github.com/Parsely/wp-parsely/blob/develop/README.md#screenshots) needs to also be updated so that the screenshots are recognised and displayed in the WPORG page; just including them in the repo isn't enough.

**Comment by acicovic** [comment]
Silly me. Looking into this.

**Review by pauarge — DISMISSED** [review]
LGTM

**Comment by acicovic** [comment]
I'll have to restore some trailing spaces and then we should probably be OK to merge this. I'll do this later today.

**Review by GaryJones — APPROVED** [review]

**Review by pauarge — APPROVED** [review]
Awesome!

**Pull request merged**
