### PR TITLE
Add a 'wp_parsely_post_category' filter

### PR DESCRIPTION
**Pull request by adamsilverstein**
Allows developers to customize the category reported for a post.

### CODE REVIEW

**Comment by msukmanowsky** [comment]
@adamsilverstein could we move the filter to before the `get_clean_parsely_page_value` call?

**Comment by adamsilverstein** [comment]
sure, that would work, but you wouldn’t be able to override the return of that function, maybe thats fine I can't recall what that function does.

I will work up an updated version with the filter before the call.

**Comment by adamsilverstein** [comment]
@msukmanowsky I updated this pull request to shift the filter to before the get_clean_parsely_page_value call.

**Comment by msukmanowsky** [comment]
Awesome, thanks @adamsilverstein!

**Comment by adamsilverstein** [comment]
You are welcome, thanks for open sourcing your plugin and also for your spiffy analytics service!

**Pull request merged**
