### PR TITLE
Prepare README.md for the wp-parsely 3.7.0 release

### PR DESCRIPTION
**Pull request by acicovic**
## Description
This PR updates the README.md in preparation for the 3.7.0 release.

## Motivation and context
Keep README.md up to date.

## How has this been tested?
No code changes.

### CODE REVIEW

**Review by mehmoodak — APPROVED** [review]

**Comment by danielabloch** [comment]
can this be moved to status = Done ?

**Comment by acicovic** [comment]
Hey @danielabloch, this has been completed for quite some time already. Where do you see it as not done?

**Comment by danielabloch** [comment]
oh yes, it appears done. I was asking if we could change its status to reflect that on the project board, which it does now (maybe I misread it earlier).

**Comment by mehmoodak** [comment]
I was the one who changed its status (did not commented because I thought status change should be mentioned in the ticket somewhere)

**Pull request merged**
